### ISSUE TITLE
兄啊，你公开发布含有reika模组的整合包最好得到他的允许

### ISSUE THREAD

**Issue by KuroPeach** [XenonDB/ManaMetal-NewHorizons_config#3]
兄啊，你公开发布含有reika模组的整合包最好得到他的允许
https://reikakalseki.github.io/minecraft/pages/perms/packrules.html

**Comment by XenonDB** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?comment=31657

早在去年10月初的時候我就已經取得了許可。
並且我也提出了與重要進度衝突的部分如何解決的方案。

**Comment by KuroPeach** [comment]
噢，了解了，只是刚看到这包，介绍里没提及，reika的列表里也无

**Comment by KuroPeach** [comment]
[XenonDB](https://github.com/XenonDB) 31a版的 ‘蓝盆子’ 你能在服务器正常使用不，我这报无法解析数据包，然后掉线，貌似又犯了之前版本的老毛病

**Comment by XenonDB** [comment]
藍盆子是哪個東西?

**Comment by KuroPeach** [comment]
chroma.stand=物品铸件台

**Comment by KuroPeach** [comment]
问题解决了，SpongeMixins的问题，它对ASM做了些修改，用来做前置修复一些bug的（
