### ISSUE TITLE
英语本地化/English Localization

### ISSUE THREAD

**Issue by Reale-ly** [XenonDB/ManaMetal-NewHorizons_config#7]
Hello! I noticed this modpack while trying to put together my own modpack based on Manametal. I'm posting this here because I couldn't find any other way to contact you. I'm an experienced translator who's planning on localizing the entirety of Manametal from scratch and I was wondering if you would be interested in an English localization for this modpack too. If you are, give me a way to contact you and we can discuss further there. (QQ, Discord, Twitter and Email are all fine)

你好！我自己在组建以 M3 为主的整合包时注意到了你的整合包。因为我找不到其联系方式，所以就在这里发帖了。我是一名有经验的译者，将来会从头全面地翻整个 M3 模组，想问你是否对为这个整合包的英语本地化感兴趣。有的话，就给我一个联络你的方式吧，我们可以在那里进一步讨论。（QQ、Discord、Twitter和电子邮件都可以）。

**Comment by XenonDB** [comment]
您好
在Discord上討論會對我比較方便。
如果您覺得可以的話，我能給你Discord的聯繫方式。

**Comment by Reale-ly** [comment]
那就用Discord吧
我的Discord是 reale_ly
